// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwb80sfpAL6topRiPKtBNm54Pj-Ao7s60',
    appId: '1:426256318070:web:804f248aa6ff40f769e957',
    messagingSenderId: '426256318070',
    projectId: 'gilbeot-51e5f',
    authDomain: 'gilbeot-51e5f.firebaseapp.com',
    storageBucket: 'gilbeot-51e5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB29uOkcdl2BCetM4ekTGsQKwQDXi1YOGg',
    appId: '1:426256318070:android:e306bbcf437915cb69e957',
    messagingSenderId: '426256318070',
    projectId: 'gilbeot-51e5f',
    storageBucket: 'gilbeot-51e5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy8RleleFOU_WT5lieop9BqXtFr2LRz7o',
    appId: '1:426256318070:ios:f33a64296877209969e957',
    messagingSenderId: '426256318070',
    projectId: 'gilbeot-51e5f',
    storageBucket: 'gilbeot-51e5f.firebasestorage.app',
    iosBundleId: 'com.example.gilbeot',
  );
}
